// TEMPORARY AUTOGENERATED FILE: easyjson stub code to make the package
// compilable during generation.

package  models

import (
  "github.com/mailru/easyjson/jwriter"
  "github.com/mailru/easyjson/jlexer"
)

func ( Posts ) MarshalJSON() ([]byte, error) { return nil, nil }
func (* Posts ) UnmarshalJSON([]byte) error { return nil }
func ( Posts ) MarshalEasyJSON(w *jwriter.Writer) {}
func (* Posts ) UnmarshalEasyJSON(l *jlexer.Lexer) {}

type EasyJSON_exporter_Posts *Posts
